<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LIN-5CG1348681" failures="1" tests="5" name="RunnerClass.RunnerClass" time="108.061" errors="0" timestamp="2024-04-17T17:45:56 IST" skipped="0">
  <testcase classname="RunnerClass.RunnerClass" name="runScenario" time="29.994"/>
  <testcase classname="RunnerClass.RunnerClass" name="runScenario" time="11.347"/>
  <testcase classname="RunnerClass.RunnerClass" name="runScenario" time="13.945"/>
  <testcase classname="RunnerClass.RunnerClass" name="runScenario" time="41.251"/>
  <testcase classname="RunnerClass.RunnerClass" name="runScenario" time="11.524">
    <failure message="expected [2] but found [1]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at HomePageStepDefinition.StepDefinitionHomePage.user_is_able_to_view_quantity_more_than_and_able_to_select_it(StepDefinitionHomePage.java:260)
at âœ½.User is able to view quantity more than 1 and able to select it.(file:///C:/Users/DGHILDIY/Desktop/Shop/src/test/resources/Features/HomePage.feature:64)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- RunnerClass.RunnerClass -->
